### ISSUE TITLE
Tournaments and other collections

### ISSUE THREAD

**Issue by charlesmudy** [jayadeepreddys/html5games#4]
Hi,

You have amazing setup and thanks for sharing this wonderful code for starters. I'm experimenting with HTML5 games and completely new to Firebase, so I'm struggling with your Collection setup?

How do you get the Tournaments / Games inserted into the firestore? The home.html screen just shows empty

Thanks in advance

**Comment by jayadeepreddys** [comment]
Hi,
Charles I will share schema for you to understand.

Schema for Battles
![image](https://user-images.githubusercontent.com/42200675/100964005-ab711180-354d-11eb-9005-1142715d40d5.png)

Schema for Tournaments
![image](https://user-images.githubusercontent.com/42200675/100964203-1a4e6a80-354e-11eb-8593-13536a993257.png)

If you are in local host change the domain key to Localhost for it to work.

**Comment by charlesmudy** [comment]
Hi Jay,

Thanks for the update, really appreciate it!

I managed to have it working with the challenges now, except the tournament which I will work on later with your update schema.

The only trick now is how to have the queue cron fetch users instantly instead of the 'every 1 minutes' ... the waiting time is just too long.
