### ISSUE TITLE
exports.queueFunction

### ISSUE THREAD

**Issue by charlesmudy** [jayadeepreddys/html5games#5]
Hello,

I have been brainstorming on the best solution for your `exports.queueFunction` on how to run it faster than waiting for every minute.

A bit lots of ideas, any possibility to call that function from an external cron job?

**Comment by jayadeepreddys** [comment]
I have tried it, But cost will shoot up for running CRON job every second. We can also try calling from external system too.

**Comment by charlesmudy** [comment]
I see. I read that too but found this information: [https://stackoverflow.com/questions/63022860/firebase-functions-interval-inside-of-an-interval-to-reduce-invocations](https://stackoverflow.com/questions/63022860/firebase-functions-interval-inside-of-an-interval-to-reduce-invocations)

`console.log("Running cron challenge...")
	var timesRun = 0;
	var interval = setInterval(() => {
		timesRun += 1;
		if (timesRun === 6) {
			console.log("Stopping cron challenge interval...")
			clearInterval(interval);
		}
		console.log("Executing challenge match...")
		getChallenges();
	}, 10000);`
